# Workflow name config
name: Node.js CI

# Definition: events -> workflow
on:
  push:
    branches:
      - main # push for main branch
  pull_request:
    branches:
      - main # pull request for main branch

# Definition: work
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x, 20.x, 22.x]

    steps:
      # Source code checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Node.js env config
      - name: Set up node.js
        uses: actions/set-up@v2
        with:
          node-version: ${{ matrix.node-version }}

      # install dependency packages
      - name: Install dependencies
        run: npm install

      # run test
      - name: Run tests
        run: npm test
